Models/ErrorViewModel.cs
namespace la_mia_pizzeria_static.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Pizza.cs
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.ComponentModel.DataAnnotations.Schema;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public int Id { get; set; }
        public string Name { get; set; }

        [Column(TypeName = "varchar(200)")]
        public string Description { get; set; }
        public string Photo { get; set; }
        public double Price { get; set; }

        public Pizza(int id, string name, string description, string photo, double price)
        {
            Id = id;
            Name = name;
            Description = description;
            Photo = photo;
            Price = price;
        }
    }
}

Controllers/HomeController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace la_mia_pizzeria_static.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PizzaController.cs
using la_mia_pizzeria_static.Data;
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Mvc;

namespace la_mia_pizzeria_static.Controllers
{
    public class PizzaController : Controller
    {
        PizzeriaDbContext db;

        public PizzaController() : base()
        {
            //Collegamento con il db
            db = new PizzeriaDbContext();
        }
        public IActionResult Index()
        {
            List<Pizza> lista = db.Pizze.ToList();

            return View(lista);
        }

        public IActionResult Detail(int id)
        {
            //selezione della pizza dal db secondo l'id passato
            Pizza pizza = db.Pizze.Where(p => p.Id == id).FirstOrDefault();

            return View(pizza);
        }
    }
}

Controllers/RazorController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewFeatures;

namespace la_mia_pizzeria_static.Controllers
{
    public partial class RazorController : Controller
    {
        public IActionResult Snacks()
        {
            return View();
        }


        
    }
}

Views/Home/Index.cshtml
<div class=" d-flex justify-content-around">

    <div class="card" style="width: 18rem;">

        <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title">Margherita</h5>
            <p class="card-text">Pomodoro, mozzarella</p>

            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>

    <div class="card" style="width: 18rem;">

        <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title"> 4 Formaggi</h5>
            <p class="card-text">Pomodoro, mozzarella, formaggi misti</p>

            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>

    <div class="card" style="width: 18rem;">

                <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title">Diavola</h5>
            <p class="card-text">Pomodoro, mozzarella, salame piccante</p>
            
            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>
</div>
<div class=" d-flex justify-content-around">
    <div class="card" style="width: 18rem;">

                <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title">Boscaiola allegra</h5>
            <p class="card-text">Mozzarella, funghi, salsiccia, funghi, provola</p>
            
            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>

    <div class="card" style="width: 18rem;">

        <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title">Capricciosa</h5>
            <p class="card-text">Mozzarella funghi, carciofini, olive, prosciutto e pomodoro</p>
            
            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>

    <div class="card" style="width: 18rem;">

        <img src="https://img.pizza/350/350" alt="mmm pizza">

        <div class="card-body">
            <h5 class="card-title">Marinara</h5>
            <p class="card-text">Pomodoro, olio, salsa, olive nere e origano</p>
            
            <div class="d-flex justify-content-between">
                <a href="#" class="btn btn-primary me-3">Acquista</a>
                <strong class="">6.99 €</strong>
            </div>
        </div>
    </div>

</div>

Views/Pizza/Detail.cshtml
@model Pizza

<a class="btn btn-primary" href="@Url.Action("index", "pizza")">Torna alla home</a>

<div class="d-flex justify-content-center">
    <div class="card mb-3 " style="width: 800px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="@Model.Photo" class="img-fluid rounded-start" alt="Pizza">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">@Model.Name</h5>
                    <p class="card-text">@Model.Description</p>
                    <strong class="card-text">@Model.Price</strong>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Pizza/Index.cshtml
@model List<Pizza>

@if (Model.Count() == 0)
{
    <h2>Non sono ci sono pizze</h2>
}
else 
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Photo
                </th>
                <th>
                    Name
                </th>
                <th>
                    Description
                </th>
                <th>
                    Price
                </th>
                <th>
                    #
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Pizza pizza in Model)
            {
                <tr>
                    @*<td><a href="@Url.Action("Detail",new {id = pizza.Id})">@pizza.Id</a></td>*@
                    <td>
                        <span>
                            @pizza.Id
                        </span>
                    </td>
                    <td class="image">
                        <img class="post-list-image" src="@pizza.Photo">
                    </td>
                    <td class="title">
                        @pizza.Name
                    </td>
                    <td class="description">
                        @pizza.Description
                    </td>
                    <td class="price">
                        @pizza.Price
                    </td>
                    <td class="detail">
                        <a href="@Url.Action("Detail", new {id = pizza.Id})" class="btn btn-primary rounded">Mostra</a>
                    </td>
                </tr>
            }
        </tbody>
            
        
    </table>
}

Views/Razor/Snacks.cshtml
@using la_mia_pizzeria_static.Controllers
@{

    Layout = "_SnacksLayout";

}


<h1>
    Snacks
</h1>

@*v1*@
<a class="btn btn-primary text-dark" asp-area="" asp-controller="Home" asp-action="Index">Return to Home</a>
@*v2*@
<a class="btn btn-primary text-dark" href="@Url.Action("Index", "Home")">Return to Home</a>

@* Snack 1*@

<div class="card my-3">
    <div class="card-header">
        Snack 1
    </div>
    <div class="card-body">
        <p>
            1. Dichiarare una variabile valorizzandola con il nostro nome.
            Dichiarare un'altra variabile valorizzandola con il nostro cognome.
            Stampare il nostro nome e cognome all'interno di un tag h2.
        </p>

        @{
            string nome = "Alessandro";
            string cognome = "Fulco";
        }

        <h2>
            @nome @cognome
        </h2>

    </div>
</div>

@* Snack 2*@

<div class="card my-3">
    <div class="card-header">
        Snack 2
    </div>
    <div class="card-body">
        <p>
            2. Creare una funzione che stampa la somma dei numeri che vanno da 1 a n (con n passato come parametro - n incluso)
            Stampare dentro uno span il risultato.
        </p>

        @{
            int SommaNumeri(int numero)
            {
                int result = 0;

                for(int i = 1; i <= numero; i++)
                {
                    result += i;
                }

                return result;
            }
        }

        <span>
            la somma dei numeri è: @SommaNumeri(5)
        </span>

    </div>
</div>

@* Snack 3*@

<div class="card my-3">
    <div class="card-header">
        Snack 3
    </div>
    <div class="card-body">

        <p>
            Contare quante volte la lettera a è presente nalla frase "nel mezzo del cammin di nostra vita" e stampare questo valore in pagina
        </p>

        @{
            int result = 0;

            string frase = "nel mezzo del cammin di nostra vita";

            for(int i = 0; i < frase.Length; i++)
            {
                if(frase[i].ToString() == "a")
                {
                    result += 1;
                }
            }
        }

        <span>
            @result
        </span>

    </div>
</div>


@* Snack 4*@

<div class="card my-3">
    <div class="card-header">
        Snack 4
    </div>
    <div class="card-body">

        <p>
            4. Creare una List<int> di 20 numeri interi (generati random da 1 a 90, 1 e 90 inclusi) e mostrare in pagina solo i numeri compresi tra 20 e 70
        </p>

        @{
            Random random = new Random();

            List<int> numeriRandom = new List<int>();

            for(int i = 1; i <= 20; i++)
            {
                numeriRandom.Add(random.Next(1, 91));
            }
        }

        @foreach (int numero in numeriRandom)
        {
            @if(numero >= 20 && numero <= 70)
            {
                <span>
                    @numero
                </span>
            }
        }
    </div>
</div>


@* Snack 5*@

<div class="card my-3">
    <div class="card-header">
        Snack 5
    </div>
    <div class="card-body">

        <p>
            Stampare in pagina la data e l'ora attuale (usando la classe DateTime) con il formato anno-mese-giorno ore:minuti:secondi
        </p>

        <span>
            @DateTime.Now.ToString("yyyy/MM/dd HH:mm:ss")
        </span>
    </div>
</div>


@* Snack 6*@

<div class="card my-3">
    <div class="card-header">
        Snack 6
    </div>
    <div class="card-body">

        <p>
            Partendo dalla data di oggi (usando la classe DateTime) stampare in pagina
                a. la data di 7 giorni fa
                b. che giorno della settimana è oggi (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
                c. che giorno della settimana sarà nello stesso giorno e mese di oggi ma tra un anno (il risultato dovrà essere il nome del giorno (Lunedì, Martedì, ...)
        </p>

        @{
            DateTime data = DateTime.Now;

            DateTime weekAgo = data.AddDays(-7);
        }

        <div>
            Una settimana fa: @weekAgo
        </div>

        <div>
            Giorno attuale: @data.DayOfWeek
        </div>

        <div>
            tra un anno: @data.AddYears(1).DayOfWeek
        </div>

    </div>
</div>


@*v1*@
<a class="btn btn-primary text-dark" asp-area="" asp-controller="Home" asp-action="Index">Return to Home</a>
@*v2*@
<a class="btn btn-primary text-dark" href="@Url.Action("Index", "Home")">Return to Home</a>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">la_mia_pizzeria_static</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pizza" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Razor" asp-action="Snacks">Snacks</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - la_mia_pizzeria_static - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_SnacksLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - la_mia_pizzeria_static</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/la_mia_pizzeria_static.styles.css" asp-append-version="true" />
</head>
<body>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>